### ISSUE TITLE
Quinitilian is messed up

### ISSUE THREAD

**Issue by neelsmith** [hcflag/latin#2]
It starts with book 12.  We need the prior 11 books.  :-)

**Comment by richardciolek** [comment]
For some reason the Tesserae edition of Quintilian had the books in the incorrect order (although the sections within the books were fine). I corrected the order, however, Quintilian still has some issues I'd like to discuss with you on Wednesday. Namely, stuff seems to get all funky and messed up when there are circumflex and iota subscripts present. Here's a preview: 
![image of messed up character set](http://i.imgur.com/TVigd7z.png)

**Comment by neelsmith** [comment]
Looks fine:  closing.
